---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      containers:
      - name: {{ .Values.postgres.name }}
        image: postgres:10.4
        imagePullPolicy: Always
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.deployment.containers.postgres_user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.deployment.containers.postgres_password }}
        - name: POSTGRES_DB
          value: {{ .Values.postgres.deployment.containers.postgres_db }}
        volumeMounts:
          - name: postgres-volume 
            mountPath: "{{ .Values.postgres.deployment.containers.postgres_volume_mount }}"   
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: pvc-postgres

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
spec:
  ports:
  - port: {{ .Values.postgres.service.port_service }}
  selector:
    app: postgres
  type: ClusterIP
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-postgres
spec:
  storageClassName: {{ .Values.postgres.name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-postgres
spec:
  storageClassName: {{ .Values.postgres.name }}
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.postgres.persistent_volume.host_path }}"