apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rabbitmq.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.rabbitmq.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.rabbitmq.name }}
    spec:
      containers:
      - name: {{ .Values.rabbitmq.name }}
        image: {{ .Values.rabbitmq.deployment.containers.image }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.name }}
spec:
  ports:
    - name: port1
      port: {{ .Values.rabbitmq.service.ports.main.port }}
    - name: port2
      port: {{ .Values.rabbitmq.service.ports.admin.port }}
  selector:
    app: {{ .Values.rabbitmq.name }}
  type: ClusterIP