apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: railspostgres
  namespace: prod
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: railspostgres
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 120
  # HPA reference (optional)
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: railspostgres
  service:
    # container port
    port: 3002
  # promote the canary without analysing it (default false)
  skipAnalysis: false
  analysis:
    # schedule interval (default 60s)
    interval: 15s
    # max number of failed metric checks before rollback
    threshold: 2
    # number of iterations
    iterations: 10
    # traffic shadowing
    mirror: true
    # total canary percentage (0-100)
    mirrorWeight: 100
    # Istio Prometheus checks
    metrics:
      - name: error-rate
        templateRef:
          name: error-rate
          namespace: istio-system
        thresholdRange:
          max: 1
        interval: 30s
      - name: latency
        templateRef:
          name: latency
          namespace: istio-system
        thresholdRange:
          max: 500
        interval: 30s
    # tests
    webhooks:
      - name: conformance-test
        type: pre-rollout
        timeout: 15s
        url: http://flagger-loadtester.prod/
        metadata:
          type: bash
          cmd: "curl -s -D - -o http://railspostgres-canary.prod:3002/products | grep products"
      - name: load-test
        type: rollout
        timeout: 15s
        url: http://flagger-loadtester.prod/
        metadata:
          type: cmd
          cmd: "hey -z 1m -q 10 -c 2 http://railspostgres-canary.prod:3002/products"
          logCmdOutput: "true"
